# Generated by Django 5.2.5 on 2025-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
