# Generated by Django 5.2.5 on 2025-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_packaging_quantity_topping_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
