# Generated by Django 5.2.5 on 2025-11-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_flavor_quantity_flavorlog_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FlavorLog',
        ),
    ]
