# Generated by Django 5.2.5 on 2025-11-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_flavor_expiration_date_alter_flavor_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
