# Generated by Django 5.2.5 on 2025-11-11 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_flavor_is_available_alter_flavor_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
