# Generated by Django 5.2.5 on 2025-11-11 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_flavor_created_at_alter_flavor_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 11, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
