# Generated by Django 5.2.5 on 2025-11-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_ingredient_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='stock',
            new_name='quantity',
        ),
    ]
