# Generated by Django 5.2.5 on 2025-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='is_available',
        ),
        migrations.AddField(
            model_name='topping',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
