# Generated by Django 5.2.5 on 2025-11-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_stock_topping_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packaging',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='is_available',
        ),
    ]
