# Generated by Django 5.2.5 on 2025-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_type_packaging_name_remove_packaging_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
