# Generated by Django 5.2.5 on 2025-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_inventory_log_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='topping',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
