# Generated by Django 5.2.5 on 2025-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_delete_inventory_remove_flavor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='critical_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='flavor',
            name='low_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
