# Generated by Django 5.2.5 on 2025-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_flavor_critical_threshold_flavor_low_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2014, max_digits=10),
            preserve_default=False,
        ),
    ]
