# Generated by Django 5.2.5 on 2025-11-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_packaging_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='price',
        ),
    ]
