# Generated by Django 5.2.5 on 2025-11-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
