# Generated by Django 5.2.5 on 2025-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('staff', models.CharField(max_length=100)),
            ],
        ),
    ]
