# Generated by Django 5.2.5 on 2025-11-08 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('LOGIN', 'Login'), ('ADD', 'Add'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
