# Generated by Django 5.2.5 on 2025-11-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
