# Generated by Django 5.2.5 on 2025-11-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loghistory',
            old_name='staff',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='staff',
            new_name='user',
        ),
    ]
